

-- TIPOPAGAMENTO
SELECT COD_TIPO_PAGAMENTO
	FROM TIPO_PAGAMENTO;
-- CATEGORIA
-- SELECT * FROM CATEGORIA;

-- SUBCATEGORIA 
-- SELECT * FROM VW_SUBCATEGORIA;
CREATE VIEW VW_SUBCATEGORIA AS 
SELECT CT.COD_CATEGORIA, CT.NME_CATEGORIA, 
		SC.COD_SUBCATEGORIA, 
		SC.NME_SUBCATEGORIA
	FROM CATEGORIA CT
	INNER JOIN 
		SUBCATEGORIA SC
    ON SC.COD_CATEGORIA = CT.COD_CATEGORIA
; 
-- UNIDADE_MEDIDA
SELECT * FROM UNIDADE_MEDIDA;

-- BAIRRO
-- CREATE
-- SELECT * FROM BAIRRO BR
--	INNER JOIN MUNICIPIO MN;


-- MUNICIPIO

-- ESTADO


-- PRODUTO 


-- USUARIO

-- CLIENTE
DROP VIEW IF EXISTS VW_CLIENTE;
CREATE VIEW VW_CLIENTE AS 
SELECT PS.COD_PESSOA, PS.NME_PESSOA, PS.COD_CPF_CNPJ, PS.NUM_TELEFONE, PS.DSC_EMAIL, 
		CL.COD_CLIENTE, CL.TPO_SEXO
	FROM CLIENTE CL
    INNER JOIN PESSOA PS
		ON CL.COD_PESSOA = PS.COD_PESSOA
    ;