-- TIPOPAGAMENTO
-- SELECT * FROM TIPO_PAGAMENTO;

-- CATEGORIA
-- SELECT * FROM CATEGORIA;

-- SUBCATEGORIA 
-- SELECT * FROM VW_SUBCATEGORIA;
CREATE VIEW VW_SUBCATEGORIA AS 
SELECT CT.COD_CATEGORIA, CT.NME_CATEGORIA, 
		SC.COD_SUBCATEGORIA, 
		SC.NME_SUBCATEGORIA
	FROM CATEGORIA CT
	INNER JOIN 
		SUBCATEGORIA SC
    ON SC.COD_CATEGORIA = CT.COD_CATEGORIA
; 
-- UNIDADE_MEDIDA
-- SELECT * FROM UNIDADE_MEDIDA;

-- PRODUTO
DROP VIEW IF EXISTS VW_PRODUTO;
CREATE VIEW VW_PRODUTO AS 
SELECT PR.COD_PRODUTO, PR.NME_PRODUTO, PR.DSC_PRODUTO, 
		SC.COD_SUBCATEGORIA, SC.NME_SUBCATEGORIA,
        CT.COD_CATEGORIA, CT.NME_CATEGORIA
	FROM PRODUTO PR 
    INNER JOIN SUBCATEGORIA SC
    ON PR.COD_SUBCATEGORIA = SC.COD_SUBCATEGORIA 
    INNER JOIN CATEGORIA CT
    ON CT.COD_CATEGORIA = SC.COD_CATEGORIA
;

-- BAIRRO
-- SELECT * FROM BAIRRO LG;

-- LOGRADOURO 
-- SELECT * FROM LOGRADOURO LG;
    
-- MUNICIPIO
-- SELECT * FROM MUNICIPIO MN; 
    
-- ESTADO
-- SELECT * FROM ESTADO;

-- LOGRADOURO   
DROP VIEW IF EXISTS VW_LOGRADOURO; 
CREATE VIEW VW_LOGRADOURO AS     
    SELECT 	LG.COD_CEP, LG.DSC_LOGRADOURO, LG.DSC_COMPLEMENTO, 
			BR.COD_BAIRRO, BR.NME_BAIRRO, 
			MN.COD_MUNICIPIO, MN.NME_MUNICIPIO, 
            ES.COD_ESTADO, ES.NME_ESTADO, ES.SGL_UF
		FROM LOGRADOURO LG
	INNER JOIN BAIRRO BR
    ON LG.COD_BAIRRO = BR.COD_BAIRRO
    INNER JOIN MUNICIPIO MN 
    ON MN.COD_MUNICIPIO = BR.COD_MUNICIPIO
    INNER JOIN ESTADO ES
    ON ES.COD_ESTADO = MN.COD_ESTADO   
;
 
-- USUARIO
SELECT * FROM VW_USUARIO;
DROP VIEW IF EXISTS VW_USUARIO;
CREATE VIEW VW_USUARIO AS
SELECT US.COD_USUARIO, US.DSC_LOGIN,  US.TPO_USUARIO, US.FLG_ATIVO,
        PS.COD_PESSOA, PS.NME_PESSOA, PS.TPO_PESSOA, 
        PS.COD_CPF_CNPJ, PS.NUM_TELEFONE
        -- CL.COD_CLIENTE,  CL.TPO_SEXO,
        -- FR.COD_FORNECEDOR, 
        -- FR.NME_RAZAO_SOCIAL
	FROM USUARIO US
	INNER JOIN PESSOA PS
    ON US.COD_PESSOA = PS.COD_PESSOA
    -- LEFT JOIN CLIENTE CL
    -- ON CL.COD_PESSOA = PS.COD_PESSOA 
    -- LEFT JOIN FORNECEDOR FR
    -- ON COD_PESSOA = PS.COD_PESSOA 
;

-- CLIENTE
DROP VIEW IF EXISTS VW_CLIENTE;
CREATE VIEW VW_CLIENTE AS 
SELECT PS.COD_PESSOA, PS.NME_PESSOA, PS.COD_CPF_CNPJ, PS.NUM_TELEFONE, PS.DSC_EMAIL, 
		CL.COD_CLIENTE, CL.TPO_SEXO
	FROM CLIENTE CL
    INNER JOIN PESSOA PS
		ON CL.COD_PESSOA = PS.COD_PESSOA
    ;
    
-- FORNECEDOR
DROP VIEW IF EXISTS VW_FORNECEDOR;
CREATE VIEW VW_FORNECEDOR AS 
SELECT PS.COD_PESSOA, PS.NME_PESSOA, PS.COD_CPF_CNPJ, PS.NUM_TELEFONE, PS.DSC_EMAIL, 
		FR.COD_FORNECEDOR, FR.NME_RAZAO_SOCIAL
	FROM FORNECEDOR FR
    INNER JOIN PESSOA PS
		ON FR.COD_PESSOA = PS.COD_PESSOA
    ;
    
    
    
