-- CRUDS IMPLEMENTADOS 
-- ESTADO 			OK
-- MUNICIPIO 		OK
-- BAIRRO			OK
-- TIPOPAGAMENTO 	OK
-- PRODUTO			OK
-- UNIDADE MEDIDA	OK
-- CATEGORIA 		OK 
-- SUBCATEGORIA		OK
-- USUARIO 			OK
-- CLIENTE			OK
-- FORNECEDOR		
-- LOGRADOURO
-- CEP

###############################################

-- TIPOPAGAMENTO
-- CALL SP_CADASTRAR_TIPO_PAGAMENTO('BTC');
-- CALL SP_ALTERAR_TIPO_PAGAMENTO(5, 'BTC');
-- CALL SP_EXCLUIR_TIPO_PAGAMENTO(5);

-- CATEGORIA
-- CALL SP_CADASTRAR_CATEGORIA('CALÇADOS');
-- CALL SP_ALTERAR_CATEGORIA(9, 'CALÇADO');
-- CALL SP_EXCLUIR_CATEGORIA(9);

-- SUBCATEGORIA 
-- CALL SP_CADASTRAR_SUBCATEGORIA('TÊNIS', 'CALÇADOS');
-- CALL SP_ALTERAR_SUBCATEGORIA(23, 'TENIS', 'CALÇADOS');
-- CALL SP_EXCLUIR_SUBCATEGORIA(22);

-- UNIDADE_MEDIDA
-- CALL SP_CADASTRAR_UNIDADE_MEDIDA('GRAMA DE ONÇA','OZ');
-- CALL SP_ALTERAR_UNIDADE_MEDIDA(6, 'LITRO', 'L');
-- CALL SP_EXCLUIR_UNIDADE_MEDIDA(7);

-- PRODUTO 
-- CALL SP_CADASTRAR_PRODUTO('TENIS ADIDAS', 'TENIS ADIDAS DJNA239DK', 'TENIS', 'UNIDADE');
-- CALL SP_ALTERAR_PRODUTO(216546531, 'TENIS ADIDAS', 'TENIS ADIDAS DJNA239DKS', 'TENISO', 'UNIDADE');
-- CALL SP_EXCLUIR_PRODUTO(216546531);

-- BAIRRO
-- CALL SP_ALTERAR_BAIRRO(35182, 'PIMENTINHAS', 'LINS');
-- CALL SP_EXCLUIR_BAIRRO(35182);

-- MUNICIPIO
-- CALL SP_CADASTRAR_MUNICIPIO('ARIRANHA', 'ES');
-- CALL SP_ALTERAR_MUNICIPIO (3557304, 'ARIRANHA', 'AM');
-- CALL SP_EXCLUIR_MUNICIPIO(3557304);

-- ESTADO
-- CALL SP_CADASTRAR_ESTADO('JUJUBA', 'JJ');
-- CALL SP_ALTERAR_ESTADO (54, 'JUJUBA', 'JA');
-- CALL SP_EXCLUIR_ESTADO(54);

-- USUARIO
-- CALL SP_CADASTRAR_USUARIO('GWINGA', '123', 'A', 1, 1);	
-- CALL SP_ALTERAR_USUARIO (1, 'LEODEEP', '123', 'A', 0, 3);	
-- CALL SP_EXCLUIR_USUARIO(2);

-- PESSOA
-- CALL SP_CADASTRAR_CLIENTE('MARCELO DANTAS', 'F', '000.000.000-00', '(11)92122-0001', 'MDANTAS@GMAIL.COM', 'M');	
-- CALL SP_ALTERAR_CLIENTE (7, 'MARCELO DANTAS', 'F', '000.000.000-00', '(11)92122-0001', 'MDANTAS@GMAIL.COM.BR', 'N');	
-- CALL SP_EXCLUIR_CLIENTE(2);
