# Generated by Django 3.2.7 on 2021-10-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.IntegerField(verbose_name=11)),
                ('nme_cliente', models.CharField(max_length=100)),
            ],
        ),
    ]
