# Generated by Django 3.2.7 on 2021-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dsc_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
