# Generated by Django 3.2.7 on 2021-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_num_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_cep',
            field=models.IntegerField(default=423423, verbose_name=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dsc_complemento',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dsc_logradouro',
            field=models.CharField(default=234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nme_bairro',
            field=models.CharField(default=1213, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nme_estado',
            field=models.CharField(default=122323, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nme_municipio',
            field=models.CharField(default=1213, max_length=100),
            preserve_default=False,
        ),
    ]
