# Generated by Django 3.2.7 on 2021-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.IntegerField(verbose_name=11)),
                ('nme_cliente', models.CharField(max_length=100)),
                ('dsc_email', models.EmailField(max_length=254)),
                ('num_telefone', models.CharField(max_length=20)),
                ('dsc_logradouro', models.CharField(max_length=255)),
                ('dsc_complemento', models.CharField(max_length=255)),
                ('cod_cep', models.IntegerField(verbose_name=11)),
                ('nme_bairro', models.CharField(max_length=255)),
                ('nme_municipio', models.CharField(max_length=100)),
                ('nme_estado', models.CharField(max_length=100)),
            ],
        ),
    ]
