
--	CREATE	DATABASE	DB_COMERCIO;
USE	DB_COMERCIO;

CREATE	TABLE	USUARIO	
(
	COD_MATRICULA	INT 			NOT NULL PRIMARY KEY,
	NME_USUARIO		VARCHAR(100),
	DSC_LOGIN		VARCHAR(30) NOT NULL, 
	DSC_HASH_SENHA	VARCHAR(255) NOT NULL,
	TPO_USUARIO		INT,
	FLG_ATIVO 		BOOL
);

CREATE	TABLE	CATEGORIA
(	
	COD_CATEGORIA	INTEGER			PRIMARY	KEY		AUTO_INCREMENT,
	NME_CATEGORIA	VARCHAR(100)	NOT	NULL	
);

-- TABLE FOTO?

CREATE	TABLE	SUBCATEGORIA
(	
	COD_SUBCATEGORIA 	INT	NOT	NULL	AUTO_INCREMENT,
	NME_SUBCATEGORIA	VARCHAR(95)	NULL,
	COD_CATEGORIA 		INT 	-- FK
)
GO
-- VALIDAR UNIFICAÇÃO DE CLIENTE E FORNECEDOR NA MESMA PESSOA
CREATE	TABLE	CLIENTE
(	
	COD_CLIENTE			INT				PRIMARY KEY	AUTO_INCREMENT,
	COD_CPF_CNPJ 		VARCHAR(15) 	NOT NULL 	-- VALIDAR 	
	NME_CLIENTE			VARCHAR(95)		NOT NULL,
	TPO_CLIENTE			CHAR(1)			NULL,		-- FISICA / JURIDICA (AVALIAR)
	DSC_EMAIL			VARCHAR(95)		NULL,
	NUM_CELULAR			VARCHAR(10)		NULL
	COD_ENDERECO 		INT 				-- FK 
);

CREATE	TABLE	FORNECEDOR
(	
	COD_FORNECEDOR				INT	NOT	NULL	AUTO_INCREMENT,
	NME_FORNECEDOR				VARCHAR(95)	NULL	,
	NME_RAZAO_SOCIAL			VARCHAR(95)	NULL	,
	COD_INSCRICAO_ESTADUAL		VARCHAR(95)	NULL	,
	COD_CNPJ					VARCHAR(95)	NULL	,
	COD_CEP						VARCHAR(95)	NULL	,
	NUM_TELEFONE 				VARCHAR(95)	NULL	,
	NUM_CEL						VARCHAR(95)	NULL	,
	DSC_EMAIL					VARCHAR(95)	NULL	,
	NRO_ENDERECO				VARCHAR(95)	NULL	,
	COD_CIDADE					INT
);

CREATE	TABLE	COMPRA
(	
	COD_COMPRA 			INT				PRIMARY KEY AUTO_INCREMENT,
	DTA_COMPRA			DATETIME		NULL	,
	COD_NOTA_FISCAL		INT				NULL	,
	VRL_TOTAL			MONEY			NULL	,
	QTD_PARCELA			INT 			NULL	,	
	TPO_STATUS_COMPRA	CHAR(1)			NULL	, /*1 -ATIVA; 2 - CANCELADA */
	COD_FORNECEDOR 		INT				NULL	,
	COD_TIPO_PAGAMENTO	INT				NULL	
);

CREATE TABLE ENDERECO 
(
	COD_CEP						INT NOT NULL PRIMARY KEY, 
	DSC_LOGRADOURO				VARCHAR(100) NULL,
	DSC_BAIRRO					VARCHAR(95)	 NULL,
	COD_CIDADE
);


CREATE	TABLE	ITEM_COMPRA
(	
	COD_ITEM_COMPRA		INT		PRIMARY KEY AUTO_INCREMENT ,
	QTD_ITEM_COMPRA		FLOAT	NULL,
	VLR_ITEM_COMPRA		MONEY	NULL,
	COD_COMPRA 			INT		NOT	NULL,
	COD_PRODUTO			INT		NOT	NULL	
);


CREATE	TABLE	ITEM_VENDA
(	
	COD_ITEM_VENDA	INT	NOT	NULL	,
	QTD_ITEM_VENDA	FLOAT	NULL	,
	VLR_ITEM_VENDA	MONEY	NULL	,
	COD_COMPRA		INT	NOT	NULL	,	--FK
	COD_PRODUTO 	INT	NOT	NULL	
)


CREATE	TABLE	PARCELA_COMPRA
(	
	COD_PARCELA_COMPRA 	INT	NOT	NULL	,
	VLR_PARCELA 		MONEY	NULL	,
	DTA_PAGAMENTO 		DATE	NULL	,
	DTA_VENCIMENTO		DATE	NULL	,
	COD_COMPRA			INT 	NOT NULL
);

CREATE	TABLE	PARCELA_VENDA
(	
	COD_PARCELA_VENDA	INT	NOT	NULL	,
	VLR_PARCELA 		MONEY	NULL	,
	DTA_PAGAMENTO 		DATE	NULL	,
	DTA_VENCIMENTO		DATE	NULL	,
	COD_COMPRA			INT 	NOT NULL
)
GO

CREATE	TABLE	PRODUTO
(	
	COD_PRODUTO 	INT	NOT	NULL	AUTO_INCREMENT,
	NME_PRODUTO 	VARCHAR(95)	NULL	,
	DSC_PRODUTO 	TEXT	NULL	,
	COD_SUBCATEGORIA
	COD_FOTO_PRODUTO -- AVALIAR 
)

-- TABLE FOTO?
CREATE	TABLE	TIPO_PAGAMENTO
(	
	COD_TIPO_PAGAMENTO INT	NOT	NULL	AUTO_INCREMENT,
	DSC_TIPO_PAGAMENTO 		VARCHAR(90)	NULL	
);


CREATE	TABLE	UNIDADE_MEDIDA
(	
	COD_UNIDADE_MEDIDA INT PRIMARY KEY AUTO_INCREMENT
	NME_UNIDADE_MEDIDA		VARCHAR(100)
)

CREATE	TABLE	VENDA
(	
	COD_VENDA 			INT PRIMARY KEY AUTO_INCREMENT, 
	DTA_VENDA 			DATETIME, 
	COD_NF				INT, 
	VLR_TOTAL			MONEY ,
	QTD_PARCELA			INT,
	SIT_VENDA			INT,
	COD_CLIENTE 		INT, -- FK 
	COD_TIPO_PAGAMENTO	INT -- FK
	-- FLG_VENDA_A_VISTA -- VERIFICAR SE FAZ SENTIDO QUE A COMPRA EM UNICA PARCELA SEJA A VISTA
);


CREATE	TABLE	CIDADE
(	
	COD_CIDADE		INTEGER			PRIMARY	KEY,
	NME_CIDADE		VARCHAR(100)	NOT	NULL,
	SGL_ESTADO		VARCHAR(2)		NOT	NULL
);
-- verificar necessiodade de visão de vendas por região (norte, nordeste, sudeste etc)

/*
-- AS FKS SERÃO IMPLEMENTADAS APÓS O FECHAMENTO DA ESTRUTURA DO MODELO DE DADOS

-- ALTER	TABLE	ITENSCOMPRA
-- 	ADD	CONSTRAINT	XPKITENSCOMPRA	PRIMARY	KEY	NONCLUSTERED	(ITC_COD	ASC,COM_COD	ASC,PRO_COD	ASC)

-- CHAVES ESTRANGEIRAS

ALTER	TABLE	ITENSVENDA
	ADD	CONSTRAINT	XPKITENSVENDA	PRIMARY	KEY	NONCLUSTERED	(ITV_COD	ASC,VEN_COD	ASC,PRO_COD	ASC)
GO


ALTER	TABLE	SUBCATEGORIA
	ADD	CONSTRAINT	XPKSUBCATEGORIA	PRIMARY	KEY	NONCLUSTERED	(SCAT_COD	ASC)
GO

ALTER	TABLE	PRODUTO
	ADD	CONSTRAINT	XPKPRODUTO	PRIMARY	KEY	NONCLUSTERED	(PRO_COD	ASC)
GO

ALTER	TABLE	PARCELASCOMPRA
	ADD	CONSTRAINT	XPKPARCELASCOMPRA	PRIMARY	KEY	CLUSTERED	(PCO_COD	ASC,COM_COD	ASC)
GO

ALTER	TABLE	TIPOPAGAMENTO
	ADD	CONSTRAINT	XPKTIPOPAGAMENTO	PRIMARY	KEY	CLUSTERED	(TPA_COD	ASC)
GO
ALTER	TABLE	UNDMEDIDA
	ADD	CONSTRAINT	XPKMEDIDA	PRIMARY	KEY	NONCLUSTERED	(UMED_COD	ASC)
GO

ALTER	TABLE	VENDA
	ADD	CONSTRAINT	XPKVENDA	PRIMARY	KEY	NONCLUSTERED	(VEN_COD	ASC)
GO


ALTER	TABLE	PARCELASVENDA
	ADD	CONSTRAINT	XPKPARCELASVENDA	PRIMARY	KEY	CLUSTERED	(VEN_COD	ASC,PVE_COD	ASC)
GO

ALTER	TABLE	COMPRA
	ADD	CONSTRAINT	R_21	FOREIGN	KEY	(FOR_COD)	REFERENCES	FORNECEDOR(FOR_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	COMPRA
	ADD	CONSTRAINT	R_24	FOREIGN	KEY	(TPA_COD)	REFERENCES	TIPOPAGAMENTO(TPA_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	ITENSCOMPRA
	ADD	CONSTRAINT	R_15	FOREIGN	KEY	(COM_COD)	REFERENCES	COMPRA(COM_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	ITENSCOMPRA
	ADD	CONSTRAINT	R_17	FOREIGN	KEY	(PRO_COD)	REFERENCES	PRODUTO(PRO_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	ITENSVENDA
	ADD	CONSTRAINT	R_13	FOREIGN	KEY	(VEN_COD)	REFERENCES	VENDA(VEN_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	ITENSVENDA
	ADD	CONSTRAINT	R_14	FOREIGN	KEY	(PRO_COD)	REFERENCES	PRODUTO(PRO_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	PARCELASCOMPRA
	ADD	CONSTRAINT	R_25	FOREIGN	KEY	(COM_COD)	REFERENCES	COMPRA(COM_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	PARCELASVENDA
	ADD	CONSTRAINT	R_22	FOREIGN	KEY	(VEN_COD)	REFERENCES	VENDA(VEN_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	PRODUTO
	ADD	CONSTRAINT	R_9	FOREIGN	KEY	(UMED_COD)	REFERENCES	UNDMEDIDA(UMED_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	PRODUTO
	ADD	CONSTRAINT	R_11	FOREIGN	KEY	(CAT_COD)	REFERENCES	CATEGORIA(CAT_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	PRODUTO
	ADD	CONSTRAINT	R_12	FOREIGN	KEY	(SCAT_COD)	REFERENCES	SUBCATEGORIA(SCAT_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	SUBCATEGORIA
	ADD	CONSTRAINT	R_10	FOREIGN	KEY	(CAT_COD)	REFERENCES	CATEGORIA(CAT_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO


ALTER	TABLE	VENDA
	ADD	CONSTRAINT	R_20	FOREIGN	KEY	(CLI_COD)	REFERENCES	CLIENTE(CLI_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO

ALTER	TABLE	VENDA
	ADD	CONSTRAINT	R_23	FOREIGN	KEY	(TPA_COD)	REFERENCES	TIPOPAGAMENTO(TPA_COD)
		ON	DELETE	NO	ACTION
		ON	UPDATE	NO	ACTION
GO
*/







