-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`BAIRRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`BAIRRO` (
  `COD_BAIRRO` 			INT(11) 			NOT NULL AUTO_INCREMENT,
  `NME_BAIRRO` 			VARCHAR(100) 		NOT NULL,
  `COD_MUNICIPIO` 		INT(11) 			NULL DEFAULT NULL,
  PRIMARY KEY PK_BAIRRO(`COD_BAIRRO`),
  INDEX `FK_BAIRRO_MUNICIPIO_IDX` (`COD_MUNICIPIO` ASC) ,
  CONSTRAINT `FK_BAIRRO_MUNICIPIO`
    FOREIGN KEY (`COD_MUNICIPIO`)
    REFERENCES `DB_COMERCIO`.`MUNICIPIO` (`COD_MUNICIPIO`)
);
