-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`CLIENTE` (
  `COD_CLIENTE` 		INT(11) 			NOT NULL AUTO_INCREMENT,
  `NME_CLIENTE` 		VARCHAR(100) 		NOT NULL,
  `TPO_CLIENTE` 		ENUM('F', 'J') 		NULL DEFAULT NULL,
  `DSC_EMAIL` 			VARCHAR(100) 		NULL DEFAULT NULL,
  `NUM_TELEFONE` 		VARCHAR(20) 		NULL DEFAULT NULL,
  `COD_BAIRRO` 			INT(11) 			NULL DEFAULT NULL,
  `TPO_SEXO` 			ENUM('M', 'F', 'N') NULL DEFAULT NULL,
  PRIMARY KEY PK_CLIENTE(`COD_CLIENTE`),
  INDEX `FK_CLIENTE_BAIRRO_IDX` (`COD_BAIRRO` ASC) ,
  CONSTRAINT `FK_CLIENTE_BAIRRO`
    FOREIGN KEY (`COD_BAIRRO`)
    REFERENCES `DB_COMERCIO`.`BAIRRO` (`COD_BAIRRO`)
);
