-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`COMPRA` (
  `COD_COMPRA` 			INT(11) 			NOT NULL AUTO_INCREMENT,
  `DTA_COMPRA` 			DATETIME 			NULL DEFAULT NULL,
  `COD_NOTA_FISCAL` 	INT(11) 			NULL DEFAULT NULL,
  `VRL_TOTAL` 			DECIMAL(10,2) 		NULL DEFAULT NULL,
  `QTD_PARCELA` 		INT(11) 			NULL DEFAULT NULL,
  `TPO_STATUS_COMPRA` 	CHAR(1) 			NULL DEFAULT NULL,
  `COD_FORNECEDOR` 		INT(11) 			NULL DEFAULT NULL,
  `COD_TIPO_PAGAMENTO` 	INT(11) 			NULL DEFAULT NULL,
  `FLG_PAGO` 			TINYINT 			NULL,
  PRIMARY KEY PK_COMPRA(`COD_COMPRA`),
  INDEX `COD_COMPRA_FORNECEDOR_IDX` (`COD_FORNECEDOR` ASC) ,
  INDEX `FK_COMPRA_TIPO_PAGAMENTO_IDX` (`COD_TIPO_PAGAMENTO` ASC) ,
  CONSTRAINT `FK_COMPRA_FORNECEDOR`
    FOREIGN KEY (`COD_FORNECEDOR`)
    REFERENCES `DB_COMERCIO`.`FORNECEDOR` (`COD_FORNECEDOR`),
  CONSTRAINT `FK_COMPRA_TIPO_PAGAMENTO`
    FOREIGN KEY (`COD_TIPO_PAGAMENTO`)
    REFERENCES `DB_COMERCIO`.`TIPO_PAGAMENTO` (`COD_TIPO_PAGAMENTO`)
);