-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`ENDERECO` (
  `COD_CEP` 			INT(11) 			NOT NULL,
  `DSC_ENDERECO` 		VARCHAR(100) 		NULL DEFAULT NULL,
  `COD_BAIRRO` 			INT 				NULL DEFAULT NULL,
  PRIMARY KEY PK_ENDERECO (`COD_CEP`),
  INDEX `FK_BAIRRO_ENDERECO_IDX` (`COD_BAIRRO` ASC) ,
  CONSTRAINT `FK_BAIRRO_ENDERECO`
    FOREIGN KEY (`COD_BAIRRO`)
    REFERENCES `DB_COMERCIO`.`BAIRRO` (`COD_BAIRRO`)
);