-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`FORNECEDOR` (
  `COD_FORNECEDOR` 		INT(11) 			NOT NULL AUTO_INCREMENT,
  `NME_FORNECEDOR` 		VARCHAR(95) 		NULL DEFAULT NULL,
  `NME_RAZAO_SOCIAL` 	VARCHAR(95) 		NULL DEFAULT NULL,
  `COD_CNPJ` 			VARCHAR(95) 		NULL DEFAULT NULL,
  `COD_CEP` 			INT 				NULL DEFAULT NULL,
  `NUM_TELEFONE` 		VARCHAR(95) 		NULL DEFAULT NULL,
  `NUM_CELULAR` 		VARCHAR(95) 		NULL DEFAULT NULL,
  `DSC_EMAIL` 			VARCHAR(95) 		NULL DEFAULT NULL,
  `NRO_ENDERECO` 		VARCHAR(95) 		NULL DEFAULT NULL,
  PRIMARY KEY PK_FORNECEDOR (`COD_FORNECEDOR`),
  INDEX `FK_FORNECEDOR_ENDERECO_IDX` (`COD_CEP` ASC) ,
  CONSTRAINT `FK_FORNECEDOR_ENDERECO`
    FOREIGN KEY (`COD_CEP`)
    REFERENCES `DB_COMERCIO`.`ENDERECO` (`COD_CEP`)
);