-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`ITEM_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`ITEM_COMPRA` (
  `COD_ITEM_COMPRA` 	INT(11) 			NOT NULL AUTO_INCREMENT,
  `QTD_ITEM_COMPRA` 	FLOAT 				NULL DEFAULT NULL,
  `VLR_ITEM_COMPRA` 	DECIMAL(10,2) 		NULL DEFAULT NULL,
  `COD_COMPRA` 			INT(11) 			NOT NULL,
  `COD_PRODUTO` 		INT(11) 			NOT NULL,
  PRIMARY KEY PK_ITEM_COMPRA(`COD_ITEM_COMPRA`),
  INDEX `FK_ITEM_COMPRA_IDX` (`COD_COMPRA` ASC) ,
  INDEX `FK_ITEM_COMPRA_PRODUTO_IDX` (`COD_PRODUTO` ASC) ,
  CONSTRAINT `FK_ITEM_COMPRA`
    FOREIGN KEY (`COD_COMPRA`)
    REFERENCES `DB_COMERCIO`.`COMPRA` (`COD_COMPRA`),
  CONSTRAINT `FK_ITEM_COMPRA_PRODUTO`
    FOREIGN KEY (`COD_PRODUTO`)
    REFERENCES `DB_COMERCIO`.`PRODUTO` (`COD_PRODUTO`)
);
