
-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`MUNICIPIO` (
  `COD_MUNICIPIO` 		INT(11) 			NOT NULL,
  `NME_CIDADE` 			VARCHAR(100) 		NOT NULL,
  `COD_ESTADO` 			INT(11) 			NOT NULL,
  PRIMARY KEY PK_MUNICIPIO (`COD_MUNICIPIO`),
  INDEX `FK_MUNICIPIO_ESTADO_IDX` (`COD_ESTADO` ASC),
  CONSTRAINT `FK_MUNICIPIO_ESTADO`
    FOREIGN KEY (`COD_ESTADO`)
    REFERENCES `DB_COMERCIO`.`ESTADO` (`COD_ESTADO`)
);
