-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`PRODUTO` (
  `COD_PRODUTO` 		INT(11) 			NOT NULL AUTO_INCREMENT,
  `NME_PRODUTO` 		VARCHAR(95) 		NULL DEFAULT NULL,
  `DSC_PRODUTO` 		VARCHAR(255) 		NULL DEFAULT NULL,
  `COD_SUBCATEGORIA` 	INT(11) 			NULL DEFAULT NULL,
  `COD_UNIDADE_MEDIDA` 	INT 				NULL,
  PRIMARY KEY PK_PRODUTO(`COD_PRODUTO`),
  INDEX `FK_PRODUTO_SUBCATEGORIA_IDX` (`COD_SUBCATEGORIA` ASC) ,
  INDEX `FK_PRODUTO_UNIDADE_MEDIDA_IDX` (`COD_UNIDADE_MEDIDA` ASC) ,
  CONSTRAINT `FK_PRODUTO_SUBCATEGORIA`
    FOREIGN KEY (`COD_SUBCATEGORIA`)
    REFERENCES `DB_COMERCIO`.`SUBCATEGORIA` (`COD_SUBCATEGORIA`),
  CONSTRAINT `FK_PRODUTO_UNIDADE_MEDIDA`
    FOREIGN KEY (`COD_UNIDADE_MEDIDA`)
    REFERENCES `DB_COMERCIO`.`UNIDADE_MEDIDA` (`COD_UNIDADE_MEDIDA`)
);
