-- -----------------------------------------------------
-- TABLE `DB_COMERCIO`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_COMERCIO`.`USUARIO` (
  `COD_USUARIO` 		INT(11) 		NOT NULL AUTO_INCREMENT,
  `NME_USUARIO` 		VARCHAR(100) 		NULL DEFAULT NULL,
  `DSC_LOGIN` 			VARCHAR(30) 		NOT NULL,
  `DSC_SENHA` 			VARCHAR(255) 		NOT NULL,
  `TPO_USUARIO` 		INT(11) 		NULL DEFAULT NULL,
  `FLG_ATIVO` 			TINYINT(1) 		NULL DEFAULT NULL,
  PRIMARY KEY PK_USUARIO(`COD_USUARIO`))
;